# This GitHub Actions workflow synchronizes the contents of a source repository to a destination repository.
name: Synchronize Repository
on:
  push:
    branches:
      - main
jobs:
  sync-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4
      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
      - name: Clone destination repository
        run: |
          git clone --depth=1 https://x-access-token:${{ secrets.DEST_REPO_PAT }}@github.com/DEST_USER/DEST_REPO.git dest_repo
          cd dest_repo
          git rm -rf .  # Remove all existing files
          rm -rf *       # Extra cleanup to remove hidden files
          cd ..
      - name: Copy source repo contents to destination repo
        run: |
          rsync -av --progress . ./dest_repo --exclude .git --exclude .github/workflows/sync-repo.yml
      - name: Commit and push changes
        run: |
          cd dest_repo
          SOURCE_REPO_NAME="${{ github.repository }}"  # Source repository name
          SOURCE_BRANCH="${{ github.ref_name }}"       # Source branch name
          SOURCE_COMMIT_HASH=$(git -C ../ rev-parse --short HEAD)  # Get short commit hash

          git add .
          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi
          git commit -m "Sync from $SOURCE_REPO_NAME ($SOURCE_BRANCH @ $SOURCE_COMMIT_HASH) [skip ci]"
          git push origin main
      - name: Cleanup workspace
        if: always()
        run: |
          echo "Cleaning up workspace..."
          rm -rf dest_repo
          echo "Cleanup complete."
