name: Sync Repository

on:
  push:
    branches:
      - main

jobs:
  sync-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source repository
        uses: actions/checkout@v4

      - name: Set up Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Clone the target repository
        run: |
          git clone https://github.com/hkg1512/transfer-test.git target-repo
          cd target-repo
          rm -rf .git .github
          git add .
          git commit -m "Sync changes from source repo - $(date)" || echo "No changes to commit"
          git push -f https://${{ secrets.TARGET_REPO_PAT }}@github.com/${{ secrets.TARGET_REPO_PATH }} main